export { default as IconArrow } from './assets/icon-arrow.svg'
export { default as IconCross } from './assets/icon-cross.svg'
export { default as IconFacebook } from './assets/icon-facebook.svg'
export { default as IconInstagram } from './assets/icon-instagram.svg'
export { default as IconMenu } from './assets/icon-menu.svg'
export { default as IconYouTube } from './assets/icon-youtube.svg'
